### PR TITLE
New entities select and number

### PR DESCRIPTION
**Pull request by sweetcorreze**
I created new number and select entities.
They allow you to control the heating and water heating mode (off, auto, forced, etc.) and the associated temperatures.

### CODE REVIEW

**Comment by lucaferrucci** [comment]
Good morning, great news, the file should be uploaded to which folder?

**Comment by dominikamann** [comment]
grafik

You can test the version by installing the pre release!

**Comment by lucaferrucci** [comment]
Ahh, ok, thank's

**Comment by dominikamann** [comment]
grafik

works great!

**Pull request merged**
